version: '3.8'
services:
  api-ebanx:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-ebanx
    entrypoint: sh -c 'npm i && npm run start:dev'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - api-ebanx-network
networks:
  api-ebanx-network:
    driver: bridge
